before_install:
- cd raid
- brew install bsdmake && ./mfiutil.sh || true
- test -f dev/mfi/mfi_ioctl.h

language: objective-c
xcode_project: SASMegaRAID.xcodeproj
xcode_scheme: SASMegaRAID
xctool_args: CONFIGURATION_BUILD_DIR=.
osx_image: xcode7.3

after_success:
- kextutil -n SASMegaRAID.kext
- mfiutil/mfiutil || true

before_deploy:
- zip -r SASMegaRAID.zip SASMegaRAID.kext mfiutil/mfiutil

deploy:
  provider: releases
  api_key:
    secure: rlS96ByJYDXd6awS2gDsIoOUE3x85jzf0XbyUwDuAwj1qviJa6/nNdta3sb7Fvb2Ll3A2qJkLbJtbsMi9HQPZHDqR5vJ5p1Rwigok0eP9lPATb7J2XLISCGzOcCFauZJvK+Ys1e/0dD7IYnTO0S8tqDZPGlp6rO6nm2zeEKyVyA=
  file: "SASMegaRAID.zip"
  skip_cleanup: true
  on:
    tags: true
